### ISSUE TITLE
Support from additional windows library

### ISSUE THREAD

**Issue by Lezardent** [smalti/gmock-win32#26]
Hi,
I am a big fan of this library and it has saved me heaps of time. However, I am now trying other functions from the WIN32 which are not in the windows.h library. For example: physicalmonitorenumerationapi.h.

Is there already a process to support this type of library?

Thanks

**Comment by smalti** [comment]
Hi, thanks for the issue reporting. Looks like such API uses a different lib-file, simple test:

```cpp
const auto p1 = &GetCurrentThreadId;
const auto p2 = GetProcAddress(LoadLibraryW(L"Kernel32.dll"), "GetCurrentThreadId");
ASSERT_EQ(LPVOID(p1), LPVOID(p2)); // OK

const auto d1 = &GetNumberOfPhysicalMonitorsFromHMONITOR;
const auto d2 = GetProcAddress(LoadLibraryW(L"dxva2.dll"), "GetNumberOfPhysicalMonitorsFromHMONITOR");
ASSERT_EQ(LPVOID(d1), LPVOID(d2)); // FAILS
```

The current patching approach is based on function addresses comparison, maybe we can try to fix it by using `IMAGE_IMPORT_BY_NAME` (`AddressOfData` in `IMAGE_THUNK_DATA32`) instead of addresses.

**Comment by Lezardent** [comment]
Is IMAGE_IMPORT_BY_NAME a function from Windows as well?

**Comment by smalti** [comment]
> Is IMAGE_IMPORT_BY_NAME a function from Windows as well?

No, it is a struct:

```cpp
typedef struct _IMAGE_IMPORT_BY_NAME {
    WORD    Hint;
    CHAR   Name[1];
} IMAGE_IMPORT_BY_NAME, *PIMAGE_IMPORT_BY_NAME;
```

I'll try to check this theory (the usage of function names instead of addresses for comparison) and I'll let you know later on the result.
